insert into carts (active, total) values (true, 0)
insert into clients (name, last_name, rut, email, authority, password, id_cart) values ('Don', 'Admin', '5842086-7', 'admin@admin.com', 'ROLE_ADMIN', '$2a$10$34BAB2zfwetWYZAupkFAouR/aFzyMrLZO0HlrDBS5TuqNr1StRdiC', 1)
insert into products (name, category, price, stock) values ('Zelda', 'Aventura', 69000, 20)
insert into products (name, category, price, stock) values ('Final Fantasy XVI', 'RPG', 79000, 5)
insert into products (name, category, price, stock) values ('Resident Evil IV', 'Acción', 50000, 10)
insert into products (name, category, price, stock) values ('Counter-Strike: Global Offensive 2', 'First Person Shooter', 100000, 1)